### ISSUE TITLE
Cancel token

### ISSUE THREAD

**Issue by xAffan** [ueman/image_provider#5]
Add support for cancel token so it doesn't keep loading images even when the widget is disposed.

**Comment by xAffan** [comment]
achievable using wrapper class

**Comment by ueman** [comment]
To the best of my knowledge this is not possible within the library and has to be done in the user code.

**Comment by xAffan** [comment]
> To the best of my knowledge this is not possible within the library and has to be done in the user code.

It kinda is, you can give an optional cancel token to the dio request so it can be cancelled. I have done it already so no need. You also need a widget that makes use of this.
